#
#███╗░░░███╗███████╗██████╗░██╗░█████╗░  ░█████╗░░█████╗░███╗░░░███╗███╗░░░███╗░█████╗░███╗░░██╗██████╗░░██████╗
#████╗░████║██╔════╝██╔══██╗██║██╔══██╗  ██╔══██╗██╔══██╗████╗░████║████╗░████║██╔══██╗████╗░██║██╔══██╗██╔════╝
#██╔████╔██║█████╗░░██║░░██║██║███████║  ██║░░╚═╝██║░░██║██╔████╔██║██╔████╔██║███████║██╔██╗██║██║░░██║╚█████╗░
#██║╚██╔╝██║██╔══╝░░██║░░██║██║██╔══██║  ██║░░██╗██║░░██║██║╚██╔╝██║██║╚██╔╝██║██╔══██║██║╚████║██║░░██║░╚═══██╗
#██║░╚═╝░██║███████╗██████╔╝██║██║░░██║  ╚█████╔╝╚█████╔╝██║░╚═╝░██║██║░╚═╝░██║██║░░██║██║░╚███║██████╔╝██████╔╝
#╚═╝░░░░░╚═╝╚══════╝╚═════╝░╚═╝╚═╝░░╚═╝  ░╚════╝░░╚════╝░╚═╝░░░░░╚═╝╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═╝░░╚══╝╚═════╝░╚═════╝░
#Dᴇᴠᴇʟᴏᴘᴇᴅ ʙʏ Mᴀɴsɪᴛᴏʜ
#Tᴡɪᴛᴛᴇʀ: @Mansitoh_Py
#Dɪsᴄᴏʀᴅ: Mansitoh#9540
#Pᴀʏᴘᴀʟ: https://paypal.me/Mansitoh
#Vᴇʀsɪᴏɴ 1.1.3
#Sᴘɪɢᴏᴛ: https://www.spigotmc.org/resources/media-commands.91042/

RecordingWebhook:
  Enabled: false
  WebhookURL: #WebhookURL
  Username: "MediaCommands"
  Author: "%Player%"
  Title: "%Player% Recording!!!"
  Color: "0xFFFFF"
  Description: "%Player% is now Recording.\n come play whit him"
  Thumbnail: #thumbail url
  Footer:
    Message: "MediaCommands"
    Link: "https://www.spigotmc.org/resources/media-commands-1-7-1-16-5.91042/"

StreamingWebhook:
  Enabled: false
  WebhookURL: #WebhookURL
  Username: "MediaCommands"
  Author: "%Player%"
  Title: "%Player% Recording!!!"
  Color: "0xFFFFF"
  Description: "%Player% is now on Stream.\n connect whit him using %Link%"
  Thumbnail: #thumbail url
  Footer:
    Message: "MediaCommands"
    Link: "https://www.spigotmc.org/resources/media-commands-1-7-1-16-5.91042/"


VideoWebhook:
  Enabled: false
  WebhookURL: #WebhookURL
  Username: "MediaCommands"
  Author: "%Player%"
  Title: "%Player% has uploaded a new Video!"
  Color: "0xFFFFF"
  Description: "%Player% has uploaded a new Video\n Link: %Link%"
  Thumbnail: #thumbail url
  Footer:
    Message: "MediaCommands"
    Link: "https://www.spigotmc.org/resources/media-commands-1-7-1-16-5.91042/"


